name: Cron only checks

on:
  schedule:
    # Weekly Wednesday 6 AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * 3'

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools sphinx-astropy
        python -m pip install -e .
    - name: Docs link check
      run: |
        cd docs
        make linkcheck
      shell: bash
